import type { Metadata } from "next";
import { NextIntlClientProvider, useLocale } from 'next-intl';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale=useLocale();
  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="alternate" href="https://kompassumzug.ch/ar" hrefLang="ar" />
        <link rel="alternate" href="https://kompassumzug.ch/en" hrefLang="en" />
      </head>
      <body style={{
        direction:locale==="en"?"ltr":"rtl",
      }}  className="min-h-full flex flex-col  ">
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
